worker_processes 4;

error_log  /app/data/log/nginx/nginx_error.log  error;
pid        /var/run/nginx.pid;


#Specifies the value for maximum file descriptors that can be opened by this process.
worker_rlimit_nofile 51200;

events
    {
        use epoll;
        worker_connections 50000;
        multi_accept on;
    }

http
    {
        log_format  main  '$http_x_forwarded_for - $remote_user [$time_local] "$request" '
             '$status $body_bytes_sent "$http_referer" '
             '"$http_user_agent"  $request_time $remote_addr'  '[$upstream_status  $upstream_addr $upstream_response_time]';
        
        log_format      szqy    '[$time_local]`$remote_addr`$http_host`$remote_user`$request`'
                        '$status`$request_length`$request_time`$body_bytes_sent`$http_referer`'
                        '$http_x_forwarded_for`$upstream_addr`$upstream_status`$upstream_response_time`$http_user_agent';


        include       /app/data/nginx/conf/mime.types;
        default_type  application/octet-stream;

        server_names_hash_bucket_size 128;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 50m;

        sendfile   on;
        tcp_nopush on;

        keepalive_timeout 60;

        tcp_nodelay on;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 256k;

        gzip on;
        gzip_min_length  1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/xml+rss;
        gzip_vary on;
        gzip_proxied   expired no-cache no-store private auth;
        gzip_disable   "MSIE [1-6]\.";

        #limit_conn_zone $binary_remote_addr zone=perip:10m;
        ##If enable limit_conn_zone,add "limit_conn perip 10;" to server section.

        server_tokens off;
        access_log /app/data/log/nginx/nginx_access.log szqy;



include /app/data/nginx/conf.d/*.conf;
}


stream {
    upstream ldap {
            server 10.213.128.97:389;
            server 10.213.129.57:389;
            server 10.213.128.98:389;
          }

    server {
       listen 1389;
       proxy_pass ldap;
       proxy_connect_timeout 1s;
    }

    upstream mariadb {
            server 10.213.128.109:3306;
          }

    server {
      listen 13307;
      proxy_pass mariadb;
      proxy_connect_timeout 1s;
    }

    upstream kdc {
            server 10.213.128.97:88;
            server 10.213.129.57:88;
          }

    server {
      listen 5088;
      proxy_pass kdc;
      proxy_connect_timeout 1s;
    }

    upstream test_esper {
            server 10.213.128.106:8400;
          }

    server {
      listen 11400;
      proxy_pass test_esper;
    }  
    upstream prod_esper {
            server 10.214.96.60:8400;
          }

    server {
      listen 11800;
      proxy_pass prod_esper;
    }
}